name: Build

on:
  push:
    branches: ['main', 'development']
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Test and Build
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build

      - name: If it fails
        if: ${{ failure() }}
        run: |
          echo '{
            "title": "Falla en el workflow: ${{ github.run_id }}",
            "body": "Este issue fue creado automáticamente por _GitHub Action workflow_. \n\n debido a un fallo en la ejecución número: _${{ github.run_id }}_.",
            "assignees": ["$GITHUB_ACTOR"],
            "labels": ["bug", "build:issue"]
            }'
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --header 'X-GitHub-Api-Version: 2022-11-28' \
          --data '{
            "title": "Falla en el workflow: ${{ github.run_id }}",
            "body": "Este issue fue creado automáticamente por _GitHub Action workflow_ **${{ github.workflow }}**. \n\n debido a un fallo en la ejecución número: [${{ github.run_id }}](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).",
            "assignees": ["${{ github.actor }}"],
            "labels": ["bug", "build:issue"]
            }'